export { default as HeroSlice } from "./HeroSlice.svelte"
export { default as AboutSlice } from "./AboutSlice.svelte"
export { default as ServicesSlice } from "./ServicesSlice.svelte"
export { default as LatestArticlesSlice } from "./LatestArticlesSlice.svelte"
export { default as ContactSlice } from "./ContactSlice.svelte"
